export const POST_UPLOAD_REQUEST = 'POST_UPLOAD_REQUEST';
export const POST_UPLOAD_SUCCESS = 'POST_UPLOAD_SUCCESS';
export const POST_UPLOAD_FAILURE = 'POST_UPLOAD_FAILURE';

export const GET_ALL_POSTS_REQUEST = 'GET_ALL_POSTS_REQUEST';
export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS';
export const GET_ALL_POSTS_FAILURE = 'GET_ALL_POSTS_FAILURE';

export const GET_MY_POSTS_REQUEST = 'GET_MY_POSTS_REQUEST';
export const GET_MY_POSTS_SUCCESS = 'GET_MY_POSTS_SUCCESS';
export const GET_MY_POSTS_FAILURE = 'GET_MY_POSTS_FAILURE';

export const GET_FAVORITE_POSTS_REQUEST = 'GET_FAVORITE_POSTS_REQUEST';
export const GET_FAVORITE_POSTS_SUCCESS = 'GET_FAVORITE_POSTS_SUCCESS';
export const GET_FAVORITE_POSTS_FAILURE = 'GET_FAVORITE_POSTS_FAILURE';
