export const GET_ALL_POSTS_REQUEST = 'GET_ALL_POSTS_REQUEST';
export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS';

export const GET_MY_POSTS_REQUEST = 'GET_MY_POSTS_REQUEST';
export const GET_MY_POSTS_SUCCESS = 'GET_MY_POSTS_SUCCESS';

export const GET_FAVORITE_POSTS_REQUEST = 'GET_FAVORITE_POSTS_REQUEST';
export const GET_FAVORITE_POSTS_SUCCESS = 'GET_FAVORITE_POSTS_SUCCESS';

export const POST_UPLOAD_REQUEST = 'POST_UPLOAD_REQUEST';
export const POST_UPLOAD_SUCCESS = 'POST_UPLOAD_SUCCESS';
export const POST_UPLOAD_FAILURE = 'POST_UPLOAD_FAILURE';

export const FAVORITE_POST_SUCCESS = 'FAVORITE_POST_SUCCESS';

export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
